### ISSUE TITLE
Cannot remove Plugin completly

### ISSUE THREAD

**Issue by elbrodark** [alexpado/OceanicMC#1]
hi,
After I installed the plugin is was not working perfectly with the other plugins, so I  wanted to remove the OceanicMC plugin.

But after deleting it there is still a water breathing bar in the middle of the screen.  Is it possible to remove it also?

**Comment by alexpado** [comment]
Run `/bossbar list`. You should see the bars created with the plugin and you should be able to remove them after.

Could you please report with which plugin you were encoutering issues ?

**Comment by elbrodark** [comment]
no I delete the logs while trying to remove the plugin sorry...
